### ISSUE TITLE
Write / Save Corrupts Workbook

### ISSUE THREAD

**Issue by jspanjaard** [qax-os/excelize#1686]
**Description**
Opening and then writing or saving the attached workbook results in it being corrupted.
[RT0001C86_CSSF SFDR Precon Report Data Collection Template v1.8.xlsx](https://github.com/qax-os/excelize/files/12847147/RT0001C86_CSSF.SFDR.Precon.Report.Data.Collection.Template.v1.8.xlsx)

**Steps to reproduce the issue:**
Tested with the following code to simply open and close.
`f, err := excelize.OpenFile("templates/RT0001C86_CSSF SFDR Precon Report Data Collection Template v1.8.xlsx")
			f.SaveAs("RT0001C86_GenerateExcelTest 3.xlsx")`

**Describe the results you received:**
When trying to recover the workbook, receive the following dialog.
<img width="447" alt="image" src="https://github.com/qax-os/excelize/assets/28752468/0bccd629-0dfc-40f5-b964-027e9898a8c9">

**Environment details:**
- Package v2.8.0
- Golang 1.20

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. If it does not work with Go 1.21.0, please reference the issues #1465, #1595, #1603, #1608, #1614, #1619, #1620, #1621, #1623, #1633, #1637, #1641, #1642, #1648, #1651, #1652, #1656, #1657, #1660, #1663 and #1670. There are some incompatible changes in the Go 1.21.0 encoding/xml library. I have given feedback to the Go team and created a patch for it (golang/go#61881), and it has been fixed on Go 1.21.1. Please using the Go 1.20.7 and previous Go released version or upgrade to Go 1.21.1 and later. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this, and I've closed this. If you have any questions, please let me know, and reopen this anytime.

**Comment by jspanjaard** [comment]
I have updated the runtime to Go 1.21.2 and tested on Go 1.19 and the issue persists. 
The issue doesn't appear when testing on a simple workbook without conditional formatting. 

I don't think this is a duplicate of the existing issues - should I reopen?

**Comment by xuri** [comment]
Thanks for your feedback. This problem has been fixed, duplicated with #1666 and #1672. Please upgrade to the master branch code, and this patch will be release in the next version.
